language: go
go: 1.1.1
before_script:
  - mkdir -p $GOPATH/src/github.com/globocom/commandmocker
  - mv * $GOPATH/src/github.com/globocom/commandmocker
script:
  - pushd $GOPATH/src/github.com/globocom/commandmocker
  - go test
